import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: "class",
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2e3132",
        "secondary": "#495c95",
        "outline-variant": "#c3c6d7",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-secondary-container": "#394c84",
        "primary-container": "#2563eb",
        "surface-tint": "#0053db",
        "on-tertiary-fixed": "#360f00",
        "secondary-fixed": "#dbe1ff",
        "error": "#ba1a1a",
        "surface-container-low": "#f2f4f6",
        "surface-dim": "#d9dadc",
        "tertiary-container": "#bc4800",
        "on-surface-variant": "#434655",
        "on-primary-container": "#eeefff",
        "tertiary": "#943700",
        "on-secondary-fixed-variant": "#31447b",
        "surface-bright": "#f8f9fb",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "on-secondary-fixed": "#00174b",
        "inverse-on-surface": "#f0f1f3",
        "secondary-container": "#acbfff",
        "on-background": "#191c1e",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e7e8ea",
        "background": "#f8f9fb",
        "secondary-fixed-dim": "#b4c5ff",
        "outline": "#737686",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb596",
        "on-primary-fixed-variant": "#003ea8",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e1e2e4",
        "on-tertiary-container": "#ffede6",
        "surface": "#f8f9fb",
        "on-primary-fixed": "#00174b",
        "primary": "#004ac6",
        "inverse-primary": "#b4c5ff",
        "surface-container": "#edeef0",
        "surface-variant": "#e1e2e4",
        "on-surface": "#191c1e",
        "tertiary-fixed": "#ffdbcd"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
};
export default config;
